### ISSUE TITLE
This repo and steam tarball are out of sync

### ISSUE THREAD

**Issue by kparal** [ValveSoftware/steam-devices#2]
The udev file in this repo doesn't reflect the udev file present in the official steam tarball:
http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.59.tar.gz

For example, this repo contains this rule:
```
# This rule is necessary for gamepad emulation; make sure you replace 'pgriffais' with a group that the user that runs Steam belongs to
KERNEL=="uinput", MODE="0660", GROUP="pgriffais", OPTIONS+="static_node=uinput"
```
while the tarball contains this rule (more modern):
```
# Steam Controller udev write access
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess"
```

There are more differences. Not only that, even the filenames differ (`steam_input.rules` vs `60-steam-input.rules` and `60-steam-vr.rules`).

This causes confusion for distributions, when deciding which udev files to install for the user. I assume this repo was created to have an opensource-friendly license for the udev file and allow PRs. Can you please make sure the files don't get out of sync? (Ideally, the latest content should be pushed here and then used for tarball generation, instead of having two sources). Thank you.

**Comment by TTimo** [comment]
Thanks. Yep I'll update with the latest steam package rules soon.

**Comment by kparal** [comment]
Thanks! When you're at it... :wink: this PR really needs to get merged to the udev file:
https://github.com/ValveSoftware/steam-for-linux/issues/4794

I've been debugging why Steam Controller doesn't work on Fedora, and even pestering the Fedora maintainer of the package (https://github.com/rpmfusion/steam/pull/10) and it really boils down to missing `OPTIONS+="static_node=uinput"`. Without it, the uinput module is not loaded automatically and the user permissions are not applied. With a rule like this:
```
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"
```
everything works out of the box (at least on Fedora).

**Comment by TTimo** [comment]
It's not clear if we can have one set of udev rules that will work on all distributions.

**Comment by kparal** [comment]
I see, distributions with systemd-udev won't support uaccess, IIUIC. Perhaps a readme file with some hints or clearly marked two different udev files here in repo could help.

**Comment by scaronni** [comment]
> Thanks. Yep I'll update with the latest steam package rules soon.

@TTimo any chance for the update matching the actual Steam tarball? I have a PR ready. Thanks.
