### ISSUE TITLE
Add newer model of PowerA switch controller

### ISSUE THREAD

**Issue by TwistedAkai** [ValveSoftware/steam-devices#27]
https://github.com/ValveSoftware/steam-devices/blob/8a3f1a0e2d208b670aafd5d65e216c71f75f1684/60-steam-input.rules#L47
We manually copied this line to create a new rule for our controller with product ID a713. Seems to work fine after 30-60 minutes of playing Dark Souls 2 on Archlinux.

> udevadm info /dev/input/js0
> P: /devices/pci0000:00/0000:00:08.1/0000:0f:00.3/usb5/5-3/5-3:1.0/0003:20D6:A713.000F/input/input31/js0
> N: input/js0
> L: 0
> S: input/by-path/pci-0000:0f:00.3-usb-0:3:1.0-joystick
> S: input/by-id/usb-Bensussen_Deutsch___Associates_Inc._BDA__NSW_Wired_controller_V1.2.3_190814_0-joystick
> E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:0f:00.3/usb5/5-3/5-3:1.0/0003:20D6:A713.000F/input/input31/js0
> E: DEVNAME=/dev/input/js0
> E: MAJOR=13
> E: MINOR=0
> E: SUBSYSTEM=input
> E: USEC_INITIALIZED=1457817941
> E: ID_INPUT=1
> E: ID_INPUT_JOYSTICK=1
> E: ID_VENDOR=Bensussen_Deutsch___Associates_Inc._BDA_
> E: ID_VENDOR_ENC=Bensussen\x20Deutsch\x20\x26\x20Associates\x2cInc.\x28BDA\x29
> E: ID_VENDOR_ID=20d6
> E: ID_MODEL=NSW_Wired_controller
> E: ID_MODEL_ENC=NSW\x20Wired\x20controller
> E: ID_MODEL_ID=a713
> E: ID_REVISION=0100
> E: ID_SERIAL=Bensussen_Deutsch___Associates_Inc._BDA__NSW_Wired_controller_V1.2.3_190814_0
> E: ID_SERIAL_SHORT=V1.2.3_190814_0
> E: ID_TYPE=hid
> E: ID_BUS=usb
> E: ID_USB_INTERFACES=:030000:
> E: ID_USB_INTERFACE_NUM=00
> E: ID_USB_DRIVER=usbhid
> E: ID_PATH=pci-0000:0f:00.3-usb-0:3:1.0
> E: ID_PATH_TAG=pci-0000_0f_00_3-usb-0_3_1_0
> E: ID_FOR_SEAT=input-pci-0000_0f_00_3-usb-0_3_1_0
> E: DEVLINKS=/dev/input/by-path/pci-0000:0f:00.3-usb-0:3:1.0-joystick /dev/input/by-id/usb-Bensussen_Deutsch___Associates_Inc._BDA__NSW_Wired_controller_V1.2.3_190814_0-joystick
> E: TAGS=:seat:uaccess:
> E: CURRENT_TAGS=:seat:uaccess:

**Comment by smcv** [comment]
This rule was added in steam-launcher 1.0.0.72, currently a public beta.
