### ISSUE TITLE
Missing the ps4 bluetooth udev rules?

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/steam-devices#8]
This script has it: https://steamcommunity.com/app/221410/discussions/0/1693795812304458372/

**Comment by kisak-valve** [comment]
Hello @romulasry, [looks fine to me](https://github.com/ValveSoftware/steam-devices/blob/47261809a52f3b53fbdcf7070cd5ab422c616dfa/60-steam-input.rules#L22-L26).

**Comment by TTimo** [comment]
to be more specific, `60-steam-input.rules` is being installed by the latest 1.0.0.62 steam package, currently in beta: https://repo.steampowered.com/steam/archive/precise/steam-launcher_latest-beta_all.deb
